#!/usr/bin/env python3
"""
ADAU1860 transport bring-up over I2C, for Pi -> codec TDM into the DSP.

WHAT THIS IS
    A serial-port + clocking init sequence DERIVED FROM UG-2257 (ADAU186x
    Hardware Reference Manual, Rev. 0, 337 pp). Every write below cites the
    register table it came from.

WHAT THIS IS NOT
    It is NOT a dump captured from working silicon, and it has NOT been run on
    hardware -- I had no route to the Pi. Treat it as a sourced first draft to
    verify, not as known-good values.

    It also does NOT configure any signal processing. The FastDSP program and
    the Tensilica DSP firmware are generated by LARK Studio from a signal flow
    and downloaded as program/parameter memory images; there is no register
    sequence that substitutes for them. This gets clocks and the serial port
    running so that data physically moves. What happens to it afterwards is
    the LARK Studio half of the job.

USAGE
    sudo python3 adau1860_init.py --bus 1 --addr 0x64 --probe
    sudo python3 adau1860_init.py --bus 1 --addr 0x64 --fs 48000 --slots 4
    sudo python3 adau1860_init.py --bus 1 --addr 0x64 --fs 48000 --slots 4 --apply

Requires: pip3 install smbus2
"""

import argparse
import sys

# --- Control port framing ------------------------------------------------
# UG-2257: "The first byte (Byte 0) of a control port write contains the 7-bit
# IC address plus R/W bit. The next four bytes (Byte 1 to Byte 4) are the
# 32-bit subaddress of the memory or register location within the ADAU186x.
# All subsequent bytes (starting with Byte 5) contain the data."
#
# Byte 0 is emitted by the kernel from the I2C address, so we send a 4-byte
# subaddress followed by data.
#
# [derived] Subaddress byte order is taken as big-endian (MSB first), the ADI
# convention and consistent with UG-2257 Figure 14/15 labelling SUBADDRESS
# BYTE1..BYTE4 in descending significance. VERIFY THIS FIRST with --probe: if
# the ID registers read back correctly, the byte order is right.

# --- Register addresses (UG-2257 register summary, p.113 onwards) ---------
VENDOR_ID      = 0x4000C000   # reset 0x41, R
DEVICE_ID1     = 0x4000C001   # reset 0x60, R
DEVICE_ID2     = 0x4000C002   # reset 0x18, R
REVISION       = 0x4000C003   # reset 0x01, R
ADC_DAC_HP_PWR = 0x4000C004   # reset 0x00, R/W  Table 125
PLL_PGA_PWR    = 0x4000C005   # reset 0x02, R/W  Table 126: [1] XTAL_EN, [0] PLL_EN
DAC_ROUTE0     = 0x4000C053   # reset 0x00, R/W  Table 190 -- reset IS "SPT0 Channel 0"
PMU_CTRL2      = 0x4000C071   # reset 0x00, R/W  [0] STARTUP_DLYCNT_BYP
STATUS2        = 0x4000C402   # R  [7] POWER_UP_COMPLETE [4] SPT0_LOCK [0] PLL_LOCK
RESETS         = 0x4000C200   # W  [4] SOFT_RESET [0] SOFT_FULL_RESET
SAI_CLK_PWR    = 0x4000C007   # reset 0x00, R/W  Table 128
CHIP_PWR       = 0x4000C00E   # reset 0x00, R/W  Table 135
CLK_CTRL1      = 0x4000C010   # reset 0xC8, R/W  Table 136
SPT0_CTRL1     = 0x4000C0E0   # reset 0x00, R/W  Table 276
SPT0_CTRL2     = 0x4000C0E1   # reset 0x00, R/W  Table 277
SPT0_CTRL3     = 0x4000C0E2   # reset 0x00, R/W  Table 278

# [derived] The 0x4000Cxxx block is byte-wide. UG-2257 says "The registers and
# RAMs in the ADAU186x are 4 bytes width, except the AON registers which is
# 1 byte width", and every reset value in this block is quoted as two hex
# digits (0x41, 0xC8, 0x10) where the 0x40000000 DMA block quotes eight
# (0x00130000). So this block is the AON set. Confirm with --probe.

# --- Clock menus (UG-2257 Table 277 / Table 278) --------------------------
# These are FIXED MENUS, not arbitrary rates. This is the constraint that
# governs the whole design.
BCLK_SRC = {3_072_000: 0b001, 6_144_000: 0b010,
            12_288_000: 0b011, 24_576_000: 0b100}
LRCLK_SRC = {8_000: 0b1000, 12_000: 0b0100, 16_000: 0b1001, 24_000: 0b0101,
             48_000: 0b0001, 96_000: 0b0010, 192_000: 0b0011,
             384_000: 0b0110, 768_000: 0b0111}

LEGAL_SLOTS = (2, 4, 6, 8)   # dwc-i2s.c rejects anything else with -EINVAL


def plan(fs, slots, slot_width=32, dac_test=False):
    """Return the register writes for a codec-master TDM config, or explain
    why the requested combination is impossible."""
    if slots not in LEGAL_SLOTS:
        sys.exit(f"slots={slots} is illegal: the Linux DesignWare I2S driver "
                 f"accepts only {LEGAL_SLOTS} (designware_i2s.h). "
                 f"Three axes therefore need 4 slots.")
    if fs not in LRCLK_SRC:
        sys.exit(f"fs={fs} cannot be generated. The ADAU1860 LRCLK generator "
                 f"offers only {sorted(LRCLK_SRC)} Hz (UG-2257 Table 278).")

    bclk = fs * slots * slot_width
    if bclk not in BCLK_SRC:
        sys.exit(f"fs={fs} x {slots} slots x {slot_width} bits needs a "
                 f"{bclk/1e6:.3f} MHz bit clock, but the ADAU1860 can only "
                 f"generate {sorted(k/1e6 for k in BCLK_SRC)} MHz "
                 f"(UG-2257 Table 277). Pick another slot count.")

    width_bits = {32: 0b00, 16: 0b01, 24: 0b10}[slot_width]

    # SPT0_CTRL1 (Table 276): [6] TRI_STATE=0, [5:4] SLOT_WIDTH,
    #                         [3:1] DATA_FORMAT=000 (I2S, delay by 1),
    #                         [0] SAI_MODE=1 (TDM)
    ctrl1 = (width_bits << 4) | 0b1

    # SPT0_CTRL2 (Table 277): [3] BCLK_POL=0 (capture on rising),
    #                         [2:0] BCLK_SRC -- non-zero = GENERATE = master
    ctrl2 = BCLK_SRC[bclk]

    # SPT0_CTRL3 (Table 278): [4] LRCLK_POL=0 (normal),
    #                         [3:0] LRCLK_SRC -- non-zero = GENERATE = master
    ctrl3 = LRCLK_SRC[fs]

    return bclk, [
        # (addr, value, why)
        #
        # ORDER MATTERS. [measured 2026-09-02 on hardware] CLK_CTRL1, PLL_PGA_PWR
        # and CHIP_PWR become READ-ONLY once the power domains are up, and
        # SOFT_FULL_RESET does NOT clear them -- only a power cycle does. So the
        # clock source must be configured BEFORE CHIP_PWR goes active, which is
        # also the order UG-2257's power-up sequence gives (step 5 then step 7).
        (PMU_CTRL2,   0x01, "STARTUP_DLYCNT_BYP=1 -- UG-2257 power-up step 3a, "
                            "required in non-self-boot mode"),
        (CLK_CTRL1,   0xC8, "XTAL_MODE=1 crystal, PLL_SOURCE=000 MCLKIN/XTAL. "
                            "Clear bit 3 (0xC0) if MCLKIN is a logic-level clock."),
        # THIS IS THE ONE THAT WAS WRONG. Reset 0x02 leaves PLL_EN=0, so the
        # BCLK/LRCLK generators have no source and the part cannot be master --
        # the symptom is a PCM that opens perfectly then EIO with hw_ptr=0.
        (PLL_PGA_PWR, 0x03, "XTAL_EN=1 | PLL_EN=1 (Table 126). MEASURED: this is "
                            "what makes STATUS2 report PLL_LOCK=1."),
        (CHIP_PWR,    0x07, "MASTER_BLOCK_EN=1, PWR_MODE=11 Active (Table 135)"),
        (SAI_CLK_PWR, 0x01, "SPT0_IN_EN=1 -- codec's serial port INPUT side, "
                            "because the Pi transmits into it (Table 128). "
                            "Use 0x03 if you also need SPT0 output."),
        (SPT0_CTRL1,  ctrl1, f"TDM, {slot_width} BCLK/slot, I2S delay-by-1 (Table 276)"),
        (SPT0_CTRL2,  ctrl2, f"generate BCLK {bclk/1e6:.3f} MHz => CODEC IS MASTER (Table 277)"),
        (SPT0_CTRL3,  ctrl3, f"generate LRCLK {fs} Hz => CODEC IS MASTER (Table 278)"),
    ] + ([
        # Presence test: prove samples physically arrive by making the chip
        # play slot 0 out of its own DAC. DAC_ROUTE0 can source a serial port
        # input channel DIRECTLY -- no DSP program, no interpolator, no ASRC.
        # (SPT0_ROUTE* cannot do the reverse: its source list is FastDSP/TDSP/
        # ASRC/ADC/DMIC/decimator/EQ only, with no serial port input, so a
        # pure digital loopback is NOT available.)
        (DAC_ROUTE0,     0x00, "DAC channel 0 <- Serial Port 0 Channel 0 (Table 190). "
                               "This is the reset value; written explicitly to be sure."),
        (ADC_DAC_HP_PWR, 0x10, "PB0_EN=1 -- DAC + headphone/line-out channel 0 on (Table 125)"),
    ] if dac_test else [])


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bus", type=int, default=1)
    ap.add_argument("--addr", type=lambda s: int(s, 0), default=0x64,
                    help="0x64..0x67, set by the ADDR1/ADDR0 pins (UG-2257 Table 23)")
    ap.add_argument("--fs", type=int, default=48000)
    ap.add_argument("--slots", type=int, default=4)
    ap.add_argument("--width", type=int, default=32, choices=(16, 24, 32))
    ap.add_argument("--probe", action="store_true", help="read ID registers and stop")
    ap.add_argument("--dac-test", action="store_true",
                    help="also route slot 0 to the DAC so arriving samples come "
                         "out of the analog output -- the simplest proof that "
                         "data physically reaches the chip")
    ap.add_argument("--apply", action="store_true",
                    help="actually write. Without it, the plan is printed only.")
    args = ap.parse_args()

    bclk, writes = plan(args.fs, args.slots, args.width, args.dac_test)

    print(f"# ADAU1860 @ I2C 0x{args.addr:02x} on bus {args.bus}")
    print(f"# TDM{args.slots}, {args.width}-bit slots, fS={args.fs} Hz, "
          f"BCLK={bclk/1e6:.3f} MHz, codec master\n")

    if not (args.probe or args.apply):
        for a, v, why in writes:
            print(f"write 0x{a:08X} = 0x{v:02X}   # {why}")
        print("\n(dry run -- pass --apply to write, --probe to read IDs first)")
        return

    try:
        from smbus2 import SMBus, i2c_msg
    except ImportError:
        sys.exit("need smbus2:  pip3 install smbus2")

    def rd(bus, reg):
        w = i2c_msg.write(args.addr, reg.to_bytes(4, "big"))
        r = i2c_msg.read(args.addr, 1)
        bus.i2c_rdwr(w, r)
        return list(r)[0]

    def wr(bus, reg, val):
        bus.i2c_rdwr(i2c_msg.write(args.addr, reg.to_bytes(4, "big") + bytes([val])))

    with SMBus(args.bus) as bus:
        ids = [(VENDOR_ID, 0x41, "VENDOR_ID"), (DEVICE_ID1, 0x60, "DEVICE_ID1"),
               (DEVICE_ID2, 0x18, "DEVICE_ID2"), (REVISION, 0x01, "REVISION")]
        ok = True
        for reg, want, name in ids:
            got = rd(bus, reg)
            flag = "OK" if got == want else "MISMATCH"
            if got != want:
                ok = False
            print(f"{name:<11} 0x{reg:08X} = 0x{got:02X}  (expect 0x{want:02X})  {flag}")

        if not ok:
            sys.exit("\nID readback wrong. Before suspecting the chip, suspect the\n"
                     "framing: 32-bit subaddress byte order, or a 1-byte vs 4-byte\n"
                     "register width in this block. Both are marked [derived] above.")
        print("\nIDs read back correctly -- 0x60,0x18 is 1860, and the 32-bit\n"
              "subaddress framing is therefore confirmed good.\n")

        if not args.apply:
            return
        import time
        for a, v, why in writes:
            wr(bus, a, v)
            back = rd(bus, a)
            flag = "OK" if back == v else "MISMATCH"
            print(f"0x{a:08X} <= 0x{v:02X}  readback 0x{back:02X}  {flag}   # {why}")
            if flag == "MISMATCH" and a in (CLK_CTRL1, PLL_PGA_PWR, CHIP_PWR):
                print("    ^ this register is latched. The part has already been "
                      "powered up\n      since its last reset and these three go "
                      "read-only. SOFT_FULL_RESET\n      does NOT clear them -- "
                      "POWER CYCLE the ADAU1860 and run this again.")
            if a == CHIP_PWR:
                time.sleep(0.4)

        s2 = rd(bus, STATUS2)
        print(f"\nSTATUS2 0x{STATUS2:08X} = 0x{s2:02X}   "
              f"POWER_UP_COMPLETE={(s2>>7)&1}  SPT0_LOCK={(s2>>4)&1}  "
              f"PLL_LOCK={s2&1}")
        if not (s2 >> 7) & 1:
            print("  POWER_UP_COMPLETE=0 -- the digital domains never came up. "
                  "Nothing will clock.")
        if not s2 & 1:
            print("  PLL_LOCK=0 -- NO SOURCE CLOCK. The BCLK/LRCLK generators have "
                  "nothing to\n  divide, so the part cannot be master and the Pi "
                  "will see EIO with hw_ptr=0.")

    if args.dac_test:
        print("\nSlot 0 now feeds the DAC. Put a scope (or headphones) on the\n"
              "analog output and send the test pattern:\n"
              "  python3 send_test_pattern.py --seconds 10 | \\\n"
              f"    aplay -D hw:$CARD,0 -f S32_LE -c {args.slots} "
              f"-r {args.fs} -t raw\n"
              "A 1 kHz tone at the output means the samples arrived.")
    print("\nNow scope BCLK and FSYNC. The Pi cannot tell you whether the codec\n"
          "is actually clocking -- in consumer mode the driver never checks.")


if __name__ == "__main__":
    main()
